[package]
name = "lazydata"
version = "0.1.0"
description = "a cli tool for database systems"
authors = ["Ye Lin Ko <yelinko.2002@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
arboard = "3.5"
clipboard = "0.5"
async-trait = "0.1.88"
color-eyre = "0.6.5"
colored = "3.0"
clap = { version = "4.5.40", features = [
    "derive",
    "cargo",
    "wrap_help",
    "unicode",
    "string",
    "unstable-styles"
] }
crossterm = { version = "0.28.1", features = ["event-stream"] }
futures = "0.3.31"
hex = "0.4.3"
inquire = "0.7.5"
once_cell = "1.21.3"
ratatui = "0.29.0"
sqlx = { version = "0.8.6", features = ["postgres", "mysql", "sqlite", "runtime-tokio","chrono", "macros","tls-rustls","uuid"] }
syntect = "5.0"
strum = "0.27"
tokio = { version = "1.45.1", features = ["full"] }
unicode-width = "0.2.0"
rmpv = "1.3.0"
tui-tree-widget = "0.23.1"
tui-textarea = "0.7.0"
serde_json = "1.0.140"
